import type { Metadata } from 'next'
import { Inter, Poppins } from 'next/font/google'
import '../styles/globals.css'
import Navbar from './components/navbar/navbar'


const poppins = Poppins({
  subsets: ['latin'],
  weight: ['600', '700'],
  variable: "--Poppins",
  display: 'swap',
});
const inter = Inter({ 
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
  display: 'swap',
  variable: "--Inter",
})

export const metadata: Metadata = {
  title: 'Travel Bookins San Andres Islas',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${poppins.variable}`}>
        <Navbar />
        {children}
      </body>
    </html>
  )
}
