import styles from './post.module.scss'

const Post = () => {
  return (
    <main className={`${styles.post}`}>
      <section className={`${styles.post__head}`}>
      </section>
      <article className={`${styles.post__body}`}>
        <div className='container'>
          <h1 className={`${styles.post__title}`}>Lorem Ipsum</h1>
          <p>Maecenas nisi neque, ornare et sagittis non, congue id justo. Ut iaculis vulputate diam, quis dignissim leo lobortis eu. Nullam porta cursus velit, a vulputate ex elementum vel. Proin eget sapien ac diam varius fringilla sed ac lectus. Duis vel orci vitae nulla iaculis scelerisque. Praesent convallis id felis sit amet pulvinar. Etiam tristique, felis vel pulvinar imperdiet, orci lectus vulputate lectus, ut tempor dui lectus et orci. Mauris quis dui sit amet lorem dictum placerat. Nunc porta pellentesque mi, sed commodo quam tincidunt eu. In quis sapien lectus. Suspendisse ligula tortor, semper vitae ante quis, facilisis luctus nibh. Sed bibendum mi vitae metus fermentum, eget molestie arcu cursus. Nullam sed lacus nec augue pellentesque porttitor nec sit amet purus. Sed dignissim consequat euismod. Sed tempor pulvinar tortor, at commodo eros aliquet sed.</p>

          <p>Etiam egestas fermentum eros, eget posuere felis sagittis ut. Morbi a lobortis lorem. In imperdiet est pellentesque, tempor metus nec, placerat sapien. Phasellus feugiat ultricies condimentum. Nunc non magna nisi. Proin non quam risus. Cras fermentum ac felis eu lobortis. Cras congue porta iaculis. Praesent scelerisque efficitur semper.</p>

          <p>Fusce quis enim erat. Sed non ornare urna. Duis a lorem cursus ipsum scelerisque dapibus. Mauris fermentum erat id congue sollicitudin. Aliquam cursus felis quis lectus condimentum, non semper justo dignissim. Praesent nec metus tempus, eleifend arcu quis, placerat urna. Aliquam facilisis ac leo eget elementum.</p>

          <p>Suspendisse sed tortor quis ante sodales laoreet sed vel sapien. Integer ultricies massa ut semper blandit. Mauris porta sed sem a finibus. Donec sagittis eros leo, in tincidunt lacus ullamcorper eu. Ut sit amet mauris eu odio dictum porttitor vitae et orci. Sed interdum, ante at sodales venenatis, arcu arcu vehicula sem, eget blandit velit dolor sed neque. Morbi et justo sodales, tempor odio lobortis, aliquet tellus. Cras nisi felis, sodales sed gravida ultrices, lobortis eu massa. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse consequat quam ut volutpat egestas.</p>

          <p>Nunc fermentum, magna quis bibendum porta, lacus tellus hendrerit metus, ut vestibulum mauris ex at lacus. Suspendisse egestas diam faucibus quam consectetur mollis. Fusce non justo vitae tellus efficitur varius porttitor sed tortor. Fusce ut ligula ut ipsum auctor fringilla. Curabitur eleifend fringilla sem. Nulla quis finibus ex. Pellentesque sit amet tincidunt mauris, vel faucibus ante. Aliquam iaculis libero turpis, eu ultricies nunc ultricies at. Nunc mi libero, luctus quis faucibus vitae, rhoncus sit amet dui. Duis semper mollis est, et scelerisque metus vehicula non. Fusce eget velit in odio elementum egestas. Vestibulum ligula massa, convallis ac scelerisque at, commodo sit amet quam.</p>

          <p>Morbi maximus nunc nunc, vitae euismod elit condimentum eu. Donec maximus tempor rutrum. Vivamus vitae finibus ipsum, quis sagittis massa. Suspendisse potenti. Nulla facilisis vitae purus sed molestie. Vestibulum ut ligula sagittis, hendrerit nulla eu, pretium justo. Donec malesuada purus tempus vestibulum pulvinar. Suspendisse elementum vel lacus non ullamcorper. Duis semper, magna quis tempor consequat, lorem arcu fermentum enim, ut consequat mauris urna in nibh. Proin vehicula metus ex, eu varius arcu dapibus id. Nulla quis viverra felis.</p>

          <p>Maecenas faucibus magna libero, in dictum mi finibus a. Sed et dui nec velit rutrum sollicitudin ut ac magna. Ut facilisis mollis lectus, a porttitor elit pharetra rhoncus. Pellentesque dignissim lorem vel est accumsan gravida. Suspendisse eleifend sodales mollis. Nunc quis arcu suscipit, dapibus lacus mollis, mollis nisi. Donec non augue auctor enim luctus ornare. Vestibulum lacinia ultrices libero non pharetra. Quisque sodales posuere mauris. In suscipit felis a risus malesuada tincidunt. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Suspendisse varius non risus vulputate faucibus. Suspendisse at viverra neque. Suspendisse porttitor nisi lacus, ac rhoncus massa mattis eu.</p>

          <p>Donec euismod vehicula mi ut elementum. Sed placerat sapien tincidunt nibh mattis, quis pulvinar massa hendrerit. Cras finibus dolor et efficitur commodo. In ipsum massa, convallis sed ultricies vitae, pharetra a libero. Sed aliquam justo ac convallis dictum. In semper congue consequat. Maecenas tempor velit at sagittis maximus. Aenean vel ex mauris. Nulla et porttitor leo. Suspendisse in elit ligula. Duis egestas mauris tortor, sit amet iaculis turpis tincidunt nec. Sed ultrices ipsum a sollicitudin interdum. Fusce auctor in lacus quis pulvinar.</p>

          <p>Curabitur maximus sed diam in aliquet. Aenean vitae nisi elit. Suspendisse non arcu id enim tristique facilisis. Vestibulum luctus viverra turpis non tempus. Praesent eget felis sed magna varius feugiat. Suspendisse potenti. Pellentesque congue, ligula vitae euismod consequat, est sem placerat justo, imperdiet vehicula ligula nulla vulputate arcu. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vestibulum rhoncus massa nec est lacinia posuere. Sed tempor metus quis mollis tristique. Phasellus pulvinar nulla ac auctor rhoncus. Proin sed tempor risus. Proin eget mattis leo. Aenean pretium, magna placerat dictum mattis, velit enim dapibus ipsum, ac scelerisque est tortor lobortis purus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.</p>

          <p>Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vestibulum tincidunt nunc feugiat, condimentum est nec, malesuada sapien. Praesent ut arcu hendrerit augue facilisis tincidunt vitae sit amet magna. Vivamus vulputate velit magna, eget hendrerit nunc laoreet vel. Donec odio neque, tempus ac nunc id, malesuada volutpat purus. Morbi a malesuada lorem. Praesent eu imperdiet justo. Fusce efficitur semper est. Vestibulum dignissim leo ac elit bibendum convallis.</p>

          <p>Curabitur sapien ante, feugiat vel neque a, hendrerit pharetra risus. In neque erat, laoreet rhoncus efficitur at, accumsan ut ex. Interdum et malesuada fames ac ante ipsum primis in faucibus. Donec quis tortor tempus, ornare ipsum ac, molestie velit. Phasellus sagittis lorem vel magna efficitur, et malesuada justo tempor. Aliquam maximus ante nec erat elementum efficitur. Donec gravida dictum neque. Quisque at elementum mi, varius pretium ipsum. Cras quis felis varius, bibendum purus non, tristique mauris. Vivamus sit amet pulvinar massa. Duis massa augue, ornare a luctus sed, placerat nec ante. Nulla tincidunt pretium interdum.</p>

          <p>Duis at sodales tortor. Nam eros magna, gravida sed blandit at, ultrices eget leo. Sed non elementum magna, id porta lorem. Sed laoreet laoreet turpis, a volutpat sapien condimentum sit amet. Nulla dapibus orci nec lacus mollis aliquam. Curabitur et nisi ut urna elementum efficitur. Sed pharetra erat id velit egestas aliquet. Curabitur lorem dui, malesuada vel congue non, porttitor eu mauris. Etiam at convallis dolor. Cras viverra consequat sodales. Aenean molestie felis ut erat efficitur, et venenatis lacus placerat.</p>

          <p>Pellentesque diam quam, ultrices eu nibh non, venenatis vehicula nisl. Nullam vitae ultricies ipsum. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nulla sit amet vulputate est, id sagittis erat. Nunc ornare at velit ut placerat. Vestibulum felis est, sodales hendrerit tellus ut, hendrerit egestas eros. Suspendisse potenti. Donec semper, nibh eu condimentum mollis, nisl augue pulvinar mauris, sed vulputate ante leo eget neque. Nulla ultricies vitae elit quis viverra. Aliquam consequat eget augue vitae volutpat. Suspendisse ac elit augue. Quisque id molestie lorem, sed pharetra lectus. Integer et tortor eu mi maximus sollicitudin. In ut quam vitae libero euismod tristique.</p>

          <p>Quisque in purus sed est sollicitudin fermentum in nec odio. Duis faucibus lectus eu augue fermentum volutpat. Sed maximus ante eu elit elementum volutpat. Donec velit sem, malesuada non felis eget, placerat eleifend turpis. Nullam congue rhoncus erat. Nunc at mi metus. Sed malesuada, purus ac varius faucibus, velit justo convallis turpis, eget faucibus lorem ligula eu augue. Praesent a congue ante, ac lacinia neque. Donec vitae pulvinar lorem, pulvinar consectetur nisl.</p>

          <p>Praesent commodo pellentesque accumsan. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Donec elementum vestibulum sapien hendrerit ultrices. Curabitur rutrum pretium ligula, eu consequat elit aliquam laoreet. Praesent ornare id felis id tempor. Mauris turpis dui, rhoncus ut urna quis, scelerisque ornare est. Cras mattis turpis non semper semper. Vestibulum auctor libero sit amet lorem rutrum auctor. Proin vel lorem velit. Praesent pulvinar laoreet urna, et ullamcorper lectus molestie id. Integer nec velit felis. Fusce ac massa eu nunc placerat faucibus sit amet et tortor. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Duis dui felis, consequat vel felis vitae, mollis porttitor urna. Ut congue at urna ut placerat. Morbi tincidunt gravida ante eget dignissim.</p>
        </div>
      </article>
    </main>
  )
}

export default Post